#index:
#    path: /
#    controller: App\Controller\DefaultController::index

test:
  path: /postform
  controller: App\Controller\PostFormController::formAff
  methods: POST

getQuest:
  path: /getQuest
  controller: App\Controller\GetQuestionController::getData
  methods: GET

token:
  path: /token
  controller: App\Controller\TokenController::token
  methods: POST
