#index:
#    path: /
#    controller: App\Controller\DefaultController::index

test:
  path: /getform
  controller: App\Controller\GetFormController::test
  methods: POST

getQuest:
  path: /getQuest
  controller: App\Controller\GetFormController::getData
  methods: POST
